version: '3'

services:
  neo4j:
    image: neo4j:4.4
    container_name: academic_paper_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app_network

  milvus:
    image: milvusdb/milvus:2.2.8
    container_name: academic_paper_milvus
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - app_network
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: academic_paper_etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: etcd --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - app_network

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    container_name: academic_paper_minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/data
    command: minio server /data
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academic_paper_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    networks:
      - app_network
    depends_on:
      - neo4j
      - milvus

  web:
    image: nginx:1.21
    container_name: academic_paper_web
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  milvus_data:
  etcd_data:
  minio_data:

